### PR TITLE
fix: 🐛 error component render error

### LINKED ISSUE #312: 渲染 ErrorComponent 时，error 报错影响全局
image

**What is the expected behavior?**
报错不影响全局

### PR DESCRIPTION
**Pull request by maoxiaoke**
Closes #312

### CODE REVIEW

File: src/AppRouter.tsx [hunk 1]
```diff
@@ -207,7 +207,7 @@ export default class AppRouter extends React.Component<AppRouterProps, AppRouter
     if (url === ICESTSRK_NOT_FOUND) {
       return renderComponent(NotFoundComponent, {});
     } else if (url === ICESTSRK_ERROR) {
-      return renderComponent(ErrorComponent, { err: this.err });
```
Comment (ClarkXia) [inline src/AppRouter.tsx:210]: ErrorComponent 默认渲染逻辑修改即可

**Review by ClarkXia — CHANGES_REQUESTED** [review]

File: src/AppRouter.tsx (hunk 1 above)
Comment (maoxiaoke) [reply src/AppRouter.tsx]: done

**Review by ClarkXia — APPROVED** [review]
