### PR TITLE
fix: 🐛 absolute path may redirect incorrect address

### LINKED ISSUE #233: 飞冰微应用：主应用中 entry 添加子应用路径不能正常展示，且报错（实测后是最新依赖包里面的问题，用之前的依赖包没有问题）
说明：
> 之前几天完全没有问题，今天重新初始化的主应用都有这个问题，把依赖包换成原来的就好了

接入方式：
```
const apps = [{
  path: '/demo',
  title: '微应用demo',
  sandbox: true,
  umd: true,
  entry: '//localhost:3333',
}];
```

报错信息：
```
VM200:87453 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:87453:13)
    at useMemo (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:106151:21)
    at Provider (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:99317:75)
    at renderWithHooks (react-dom.development.js:14803)
    at mountIndeterminateComponent (react-dom.development.js:17482)
    at beginWork (react-dom.development.js:18596)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22154)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at scheduleUpdateOnFiber (react-dom.development.js:21199)
    at dispatchAction (react-dom.development.js:15660)
    at handleAppLeave (runtime.js:157)
    at AppRoute._this.unmountApp (AppRoute.js:84)
    at AppRoute../node_modules/@ice/stark/lib/AppRoute.js.AppRoute.componentWillUnmount (AppRoute.js:148)
    at callComponentWillUnmountWithTimer (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:92309:12)
    at HTMLUnknownElement.callCallback (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:72917:14)
    at Object.invokeGuardedCallbackDev (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:72966:16)
    at invokeGuardedCallback (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:73021:31)
    at safelyCallComponentWillUnmount (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:92316:5)
    at commitUnmount (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:92838:11)
    at commitNestedUnmounts (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:92892:5)
    at unmountHostComponents (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:93172:7)
    at commitDeletion (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:93229:5)
    at commitMutationEffects (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:95511:11)
    at HTMLUnknownElement.callCallback (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:72917:14)
    at Object.invokeGuardedCallbackDev (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:72966:16)
    at invokeGuardedCallback (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:73021:31)
    at commitRootImpl (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:95238:9)
    at unstable_runWithPriority (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:109176:12)
    at runWithPriority$1 (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:83768:10)
    at commitRoot (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:95110:3)
    at finishSyncRender (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:94536:3)
    at performSyncWorkOnRoot (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:94522:7)
    at eval (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:83818:24)
    at unstable_runWithPriority (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:109176:12)
    at runWithPriority$1 (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:83768:10)
    at flushSyncCallbackQueueImpl (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:83813:7)
    at flushSyncCallbackQueue (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:83801:3)
    at scheduleUpdateOnFiber (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:93928:9)
    at updateContainer (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:97102:3)
    at legacyRenderSubtreeIntoContainer (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:97503:5)
throwInvalidHookError @ VM200:87453
useMemo @ VM200:106151
Provider @ VM200:99317
renderWithHooks @ react-dom.development.js:14803
mountIndeterminateComponent @ react-dom.development.js:17482
beginWork @ react-dom.development.js:18596
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
dispatchAction @ react-dom.development.js:15660
handleAppLeave @ runtime.js:157
AppRoute._this.unmountApp @ AppRoute.js:84
./node_modules/@ice/stark/lib/AppRoute.js.AppRoute.componentWillUnmount @ AppRoute.js:148
callComponentWillUnmountWithTimer @ VM200:92309
callCallback @ VM200:72917
invokeGuardedCallbackDev @ VM200:72966
invokeGuardedCallback @ VM200:73021
safelyCallComponentWillUnmount @ VM200:92316
commitUnmount @ VM200:92838
commitNestedUnmounts @ VM200:92892
unmountHostComponents @ VM200:93172
commitDeletion @ VM200:93229
commitMutationEffects @ VM200:95511
callCallback @ VM200:72917
invokeGuardedCallbackDev @ VM200:72966
invokeGuardedCallback @ VM200:73021
commitRootImpl @ VM200:95238
unstable_runWithPriority @ VM200:109176
runWithPriority$1 @ VM200:83768
commitRoot @ VM200:95110
finishSyncRender @ VM200:94536
performSyncWorkOnRoot @ VM200:94522
eval @ VM200:83818
unstable_runWithPriority @ VM200:109176
runWithPriority$1 @ VM200:83768
flushSyncCallbackQueueImpl @ VM200:83813
flushSyncCallbackQueue @ VM200:83801
scheduleUpdateOnFiber @ VM200:93928
updateContainer @ VM200:97102
legacyRenderSubtreeIntoContainer @ VM200:97503
render @ VM200:97569
_render @ VM200:72669
renderInBrowser @ VM200:72656
eval @ VM200:72621
step @ VM200:72561
eval @ VM200:72542
eval @ VM200:72536
./node_modules/react-app-renderer/lib/renderer.js.__awaiter @ VM200:72532
reactAppRenderer @ VM200:72585
runApp @ VM200:1876
./src/app.tsx @ VM200:119114
__webpack_require__ @ VM200:792
fn @ VM200:103
1 @ VM200:119952
__webpack_require__ @ VM200:792
eval @ VM200:859
eval @ VM200:862
./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox @ index.js:165
(anonymous) @ umdLoader.js:26
(anonymous) @ umdLoader.js:19
Promise.then (async)
loadUmdModule @ umdLoader.js:14
(anonymous) @ apps.js:153
step @ apps.js:44
(anonymous) @ apps.js:25
fulfilled @ apps.js:16
Promise.then (async)
step @ apps.js:18
fulfilled @ apps.js:16
Promise.then (async)
step @ apps.js:18
(anonymous) @ apps.js:19
./node_modules/@ice/stark/lib/apps.js.__awaiter @ apps.js:15
loadAppModule @ apps.js:121
(anonymous) @ apps.js:271
step @ apps.js:44
(anonymous) @ apps.js:25
(anonymous) @ apps.js:19
./node_modules/@ice/stark/lib/apps.js.__awaiter @ apps.js:15
createMicroApp @ apps.js:246
AppRoute._this.renderChild @ AppRoute.js:96
AppRoute._this.mountApp @ AppRoute.js:77
./node_modules/@ice/stark/lib/AppRoute.js.AppRoute.componentDidMount @ AppRoute.js:113
commitLifeCycles @ react-dom.development.js:19814
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
Show 72 more frames
apps.js:382 [icestark] can not find app /demo when call unloadMicroApp
index.js:1 The above error occurred in the <Provider> component:
    in Provider
    in Provider
    in AuthStoreProvider
    in ConfigProvider
    in addProvider
    in Unknown
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
console.<computed> @ VM200:97798
logCapturedError @ react-dom.development.js:19527
logError @ react-dom.development.js:19564
update.callback @ react-dom.development.js:20708
callCallback @ react-dom.development.js:12490
commitUpdateQueue @ react-dom.development.js:12511
commitLifeCycles @ react-dom.development.js:19883
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
dispatchAction @ react-dom.development.js:15660
handleAppLeave @ runtime.js:157
AppRoute._this.unmountApp @ AppRoute.js:84
./node_modules/@ice/stark/lib/AppRoute.js.AppRoute.componentWillUnmount @ AppRoute.js:148
callComponentWillUnmountWithTimer @ VM200:92309
callCallback @ VM200:72917
invokeGuardedCallbackDev @ VM200:72966
invokeGuardedCallback @ VM200:73021
safelyCallComponentWillUnmount @ VM200:92316
commitUnmount @ VM200:92838
commitNestedUnmounts @ VM200:92892
unmountHostComponents @ VM200:93172
commitDeletion @ VM200:93229
commitMutationEffects @ VM200:95511
callCallback @ VM200:72917
invokeGuardedCallbackDev @ VM200:72966
invokeGuardedCallback @ VM200:73021
commitRootImpl @ VM200:95238
unstable_runWithPriority @ VM200:109176
runWithPriority$1 @ VM200:83768
commitRoot @ VM200:95110
finishSyncRender @ VM200:94536
performSyncWorkOnRoot @ VM200:94522
eval @ VM200:83818
unstable_runWithPriority @ VM200:109176
runWithPriority$1 @ VM200:83768
flushSyncCallbackQueueImpl @ VM200:83813
flushSyncCallbackQueue @ VM200:83801
scheduleUpdateOnFiber @ VM200:93928
updateContainer @ VM200:97102
legacyRenderSubtreeIntoContainer @ VM200:97503
render @ VM200:97569
_render @ VM200:72669
renderInBrowser @ VM200:72656
eval @ VM200:72621
step @ VM200:72561
eval @ VM200:72542
eval @ VM200:72536
./node_modules/react-app-renderer/lib/renderer.js.__awaiter @ VM200:72532
reactAppRenderer @ VM200:72585
runApp @ VM200:1876
./src/app.tsx @ VM200:119114
__webpack_require__ @ VM200:792
fn @ VM200:103
1 @ VM200:119952
__webpack_require__ @ VM200:792
eval @ VM200:859
eval @ VM200:862
./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox @ index.js:165
(anonymous) @ umdLoader.js:26
(anonymous) @ umdLoader.js:19
Promise.then (async)
loadUmdModule @ umdLoader.js:14
(anonymous) @ apps.js:153
step @ apps.js:44
(anonymous) @ apps.js:25
fulfilled @ apps.js:16
Promise.then (async)
step @ apps.js:18
fulfilled @ apps.js:16
Promise.then (async)
step @ apps.js:18
(anonymous) @ apps.js:19
./node_modules/@ice/stark/lib/apps.js.__awaiter @ apps.js:15
loadAppModule @ apps.js:121
(anonymous) @ apps.js:271
step @ apps.js:44
(anonymous) @ apps.js:25
(anonymous) @ apps.js:19
./node_modules/@ice/stark/lib/apps.js.__awaiter @ apps.js:15
createMicroApp @ apps.js:246
AppRoute._this.renderChild @ AppRoute.js:96
AppRoute._this.mountApp @ AppRoute.js:77
./node_modules/@ice/stark/lib/AppRoute.js.AppRoute.componentDidMount @ AppRoute.js:113
commitLifeCycles @ react-dom.development.js:19814
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
Show 77 more frames
react-dom.development.js:11102 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:87453:13)
    at useMemo (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:106151:21)
    at Provider (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:99317:75)
    at renderWithHooks (react-dom.development.js:14803)
    at mountIndeterminateComponent (react-dom.development.js:17482)
    at beginWork (react-dom.development.js:18596)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22154)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at scheduleUpdateOnFiber (react-dom.development.js:21199)
    at dispatchAction (react-dom.development.js:15660)
    at handleAppLeave (runtime.js:157)
    at AppRoute._this.unmountApp (AppRoute.js:84)
    at AppRoute../node_modules/@ice/stark/lib/AppRoute.js.AppRoute.componentWillUnmount (AppRoute.js:148)
    at callComponentWillUnmountWithTimer (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:92309:12)
    at HTMLUnknownElement.callCallback (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:72917:14)
    at Object.invokeGuardedCallbackDev (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:72966:16)
    at invokeGuardedCallback (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:73021:31)
    at safelyCallComponentWillUnmount (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:92316:5)
    at commitUnmount (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:92838:11)
    at commitNestedUnmounts (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:92892:5)
    at unmountHostComponents (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:93172:7)
    at commitDeletion (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:93229:5)
    at commitMutationEffects (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:95511:11)
    at HTMLUnknownElement.callCallback (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:72917:14)
    at Object.invokeGuardedCallbackDev (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:72966:16)
    at invokeGuardedCallback (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:73021:31)
    at commitRootImpl (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:95238:9)
    at unstable_runWithPriority (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:109176:12)
    at runWithPriority$1 (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:83768:10)
    at commitRoot (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:95110:3)
    at finishSyncRender (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:94536:3)
    at performSyncWorkOnRoot (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:94522:7)
    at eval (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:83818:24)
    at unstable_runWithPriority (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:109176:12)
    at runWithPriority$1 (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:83768:10)
    at flushSyncCallbackQueueImpl (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:83813:7)
    at flushSyncCallbackQueue (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:83801:3)
    at scheduleUpdateOnFiber (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:93928:9)
    at updateContainer (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:97102:3)
    at legacyRenderSubtreeIntoContainer (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (index.js:163), <anonymous>:97503:5)
throwInvalidHookError @ VM200:87453
useMemo @ VM200:106151
Provider @ VM200:99317
renderWithHooks @ react-dom.development.js:14803
mountIndeterminateComponent @ react-dom.development.js:17482
beginWork @ react-dom.development.js:18596
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
dispatchAction @ react-dom.development.js:15660
handleAppLeave @ runtime.js:157
AppRoute._this.unmountApp @ AppRoute.js:84
./node_modules/@ice/stark/lib/AppRoute.js.AppRoute.componentWillUnmount @ AppRoute.js:148
callComponentWillUnmountWithTimer @ VM200:92309
callCallback @ VM200:72917
invokeGuardedCallbackDev @ VM200:72966
invokeGuardedCallback @ VM200:73021
safelyCallComponentWillUnmount @ VM200:92316
commitUnmount @ VM200:92838
commitNestedUnmounts @ VM200:92892
unmountHostComponents @ VM200:93172
commitDeletion @ VM200:93229
commitMutationEffects @ VM200:95511
callCallback @ VM200:72917
invokeGuardedCallbackDev @ VM200:72966
invokeGuardedCallback @ VM200:73021
commitRootImpl @ VM200:95238
unstable_runWithPriority @ VM200:109176
runWithPriority$1 @ VM200:83768
commitRoot @ VM200:95110
finishSyncRender @ VM200:94536
performSyncWorkOnRoot @ VM200:94522
eval @ VM200:83818
unstable_runWithPriority @ VM200:109176
runWithPriority$1 @ VM200:83768
flushSyncCallbackQueueImpl @ VM200:83813
flushSyncCallbackQueue @ VM200:83801
scheduleUpdateOnFiber @ VM200:93928
updateContainer @ VM200:97102
legacyRenderSubtreeIntoContainer @ VM200:97503
render @ VM200:97569
_render @ VM200:72669
renderInBrowser @ VM200:72656
eval @ VM200:72621
step @ VM200:72561
eval @ VM200:72542
eval @ VM200:72536
./node_modules/react-app-renderer/lib/renderer.js.__awaiter @ VM200:72532
reactAppRenderer @ VM200:72585
runApp @ VM200:1876
./src/app.tsx @ VM200:119114
__webpack_require__ @ VM200:792
fn @ VM200:103
1 @ VM200:119952
__webpack_require__ @ VM200:792
eval @ VM200:859
eval @ VM200:862
./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox @ index.js:165
(anonymous) @ umdLoader.js:26
(anonymous) @ umdLoader.js:19
Promise.then (async)
loadUmdModule @ umdLoader.js:14
(anonymous) @ apps.js:153
step @ apps.js:44
(anonymous) @ apps.js:25
fulfilled @ apps.js:16
Promise.then (async)
step @ apps.js:18
fulfilled @ apps.js:16
Promise.then (async)
step @ apps.js:18
(anonymous) @ apps.js:19
./node_modules/@ice/stark/lib/apps.js.__awaiter @ apps.js:15
loadAppModule @ apps.js:121
(anonymous) @ apps.js:271
step @ apps.js:44
(anonymous) @ apps.js:25
(anonymous) @ apps.js:19
./node_modules/@ice/stark/lib/apps.js.__awaiter @ apps.js:15
createMicroApp @ apps.js:246
AppRoute._this.renderChild @ AppRoute.js:96
AppRoute._this.mountApp @ AppRoute.js:77
./node_modules/@ice/stark/lib/AppRoute.js.AppRoute.componentDidMount @ AppRoute.js:113
commitLifeCycles @ react-dom.development.js:19814
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
Show 72 more frames
VM200:80336 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChildFromContainer (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:80336:15)
    at unmountHostComponents (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:93176:9)
    at commitDeletion (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:93229:5)
    at commitMutationEffects (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:95511:11)
    at HTMLUnknownElement.callCallback (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:72917:14)
    at Object.invokeGuardedCallbackDev (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:72966:16)
    at invokeGuardedCallback (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:73021:31)
    at commitRootImpl (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:95238:9)
    at unstable_runWithPriority (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:109176:12)
    at runWithPriority$1 (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:83768:10)
    at commitRoot (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:95110:3)
    at finishSyncRender (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:94536:3)
    at performSyncWorkOnRoot (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:94522:7)
    at eval (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:83818:24)
    at unstable_runWithPriority (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:109176:12)
    at runWithPriority$1 (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:83768:10)
    at flushSyncCallbackQueueImpl (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:83813:7)
    at flushSyncCallbackQueue (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:83801:3)
    at scheduleUpdateOnFiber (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:93928:9)
    at updateContainer (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:97102:3)
    at legacyRenderSubtreeIntoContainer (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:97503:5)
    at Object.render (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:97569:10)
    at _render (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:72669:71)
    at renderInBrowser (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:72656:16)
    at eval (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:72621:21)
    at step (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:72561:23)
    at Object.eval [as next] (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:72542:53)
    at eval (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:72536:71)
    at new Promise (<anonymous>)
    at ./node_modules/react-app-renderer/lib/renderer.js.__awaiter (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:72532:12)
    at reactAppRenderer (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:72585:12)
    at runApp (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:1876:3)
    at Module../src/app.tsx (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:119114:53)
    at __webpack_require__ (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:792:30)
    at fn (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:103:20)
    at Object.1 (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:119952:18)
    at __webpack_require__ (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:792:30)
    at eval (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:859:37)
    at Proxy.eval (eval at ./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41756:28), <anonymous>:862:10)
    at Sandbox../node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox (http://localhost:3335/js/index.js:41758:17)
    at http://localhost:3335/js/index.js:44236:29
    at Array.forEach (<anonymous>)
    at http://localhost:3335/js/index.js:44229:25
removeChildFromContainer @ VM200:80336
unmountHostComponents @ VM200:93176
commitDeletion @ VM200:93229
commitMutationEffects @ VM200:95511
callCallback @ VM200:72917
invokeGuardedCallbackDev @ VM200:72966
invokeGuardedCallback @ VM200:73021
commitRootImpl @ VM200:95238
unstable_runWithPriority @ VM200:109176
runWithPriority$1 @ VM200:83768
commitRoot @ VM200:95110
finishSyncRender @ VM200:94536
performSyncWorkOnRoot @ VM200:94522
eval @ VM200:83818
unstable_runWithPriority @ VM200:109176
runWithPriority$1 @ VM200:83768
flushSyncCallbackQueueImpl @ VM200:83813
flushSyncCallbackQueue @ VM200:83801
scheduleUpdateOnFiber @ VM200:93928
updateContainer @ VM200:97102
legacyRenderSubtreeIntoContainer @ VM200:97503
render @ VM200:97569
_render @ VM200:72669
renderInBrowser @ VM200:72656
eval @ VM200:72621
step @ VM200:72561
eval @ VM200:72542
eval @ VM200:72536
./node_modules/react-app-renderer/lib/renderer.js.__awaiter @ VM200:72532
reactAppRenderer @ VM200:72585
runApp @ VM200:1876
./src/app.tsx @ VM200:119114
__webpack_require__ @ VM200:792
fn @ VM200:103
1 @ VM200:119952
__webpack_require__ @ VM200:792
eval @ VM200:859
eval @ VM200:862
./node_modules/@ice/sandbox/lib/index.js.Sandbox.execScriptInSandbox @ index.js:165
(anonymous) @ umdLoader.js:26
(anonymous) @ umdLoader.js:19
Promise.then (async)
loadUmdModule @ umdLoader.js:14
(anonymous) @ apps.js:153
step @ apps.js:44
(anonymous) @ apps.js:25
fulfilled @ apps.js:16
Promise.then (async)
step @ apps.js:18
fulfilled @ apps.js:16
Promise.then (async)
step @ apps.js:18
(anonymous) @ apps.js:19
./node_modules/@ice/stark/lib/apps.js.__awaiter @ apps.js:15
loadAppModule @ apps.js:121
(anonymous) @ apps.js:271
step @ apps.js:44
(anonymous) @ apps.js:25
(anonymous) @ apps.js:19
./node_modules/@ice/stark/lib/apps.js.__awaiter @ apps.js:15
createMicroApp @ apps.js:246
AppRoute._this.renderChild @ AppRoute.js:96
AppRoute._this.mountApp @ AppRoute.js:77
./node_modules/@ice/stark/lib/AppRoute.js.AppRoute.componentDidMount @ AppRoute.js:113
commitLifeCycles @ react-dom.development.js:19814
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
Show 43 more frames
```

接入方式：
```
const apps = [{
  path: '/demo',
  title: '微应用demo',
  //sandbox: true,
  //umd: true,
  entry: '//localhost:3333',
}];
```

报错信息：
```
react-dom.development.js:14724 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (VM207 index.js:87451)
    at useMemo (VM207 index.js:106149)
    at Provider (VM207 index.js:99315)
    at renderWithHooks (VM207 index.js:87530)
    at mountIndeterminateComponent (VM207 index.js:90209)
    at beginWork (VM207 index.js:91323)
    at HTMLUnknownElement.callCallback (VM207 index.js:72915)
    at Object.invokeGuardedCallbackDev (VM207 index.js:72964)
    at invokeGuardedCallback (VM207 index.js:73019)
    at beginWork$1 (VM207 index.js:95930)
    at performUnitOfWork (VM207 index.js:94881)
    at workLoopSync (VM207 index.js:94857)
    at performSyncWorkOnRoot (VM207 index.js:94483)
    at VM207 index.js:83816
    at unstable_runWithPriority (VM207 index.js:109174)
    at runWithPriority$1 (VM207 index.js:83766)
    at flushSyncCallbackQueueImpl (VM207 index.js:83811)
    at flushSyncCallbackQueue (VM207 index.js:83799)
    at scheduleUpdateOnFiber (VM207 index.js:93926)
    at dispatchAction (VM207 index.js:88387)
    at handleAppLeave (VM207 index.js:49981)
    at AppRoute._this.unmountApp (VM207 index.js:42247)
    at AppRoute../node_modules/@ice/stark/lib/AppRoute.js.AppRoute.componentWillUnmount (VM207 index.js:42311)
    at callComponentWillUnmountWithTimer (VM207 index.js:92307)
    at HTMLUnknownElement.callCallback (VM207 index.js:72915)
    at Object.invokeGuardedCallbackDev (VM207 index.js:72964)
    at invokeGuardedCallback (VM207 index.js:73019)
    at safelyCallComponentWillUnmount (VM207 index.js:92314)
    at commitUnmount (VM207 index.js:92836)
    at commitNestedUnmounts (VM207 index.js:92890)
    at unmountHostComponents (VM207 index.js:93170)
    at commitDeletion (VM207 index.js:93227)
    at commitMutationEffects (VM207 index.js:95509)
    at HTMLUnknownElement.callCallback (VM207 index.js:72915)
    at Object.invokeGuardedCallbackDev (VM207 index.js:72964)
    at invokeGuardedCallback (VM207 index.js:73019)
    at commitRootImpl (VM207 index.js:95236)
    at unstable_runWithPriority (VM207 index.js:109174)
    at runWithPriority$1 (VM207 index.js:83766)
    at commitRoot (VM207 index.js:95108)
    at finishSyncRender (VM207 index.js:94534)
    at performSyncWorkOnRoot (VM207 index.js:94520)
    at VM207 index.js:83816
    at unstable_runWithPriority (VM207 index.js:109174)
    at runWithPriority$1 (VM207 index.js:83766)
    at flushSyncCallbackQueueImpl (VM207 index.js:83811)
    at flushSyncCallbackQueue (VM207 index.js:83799)
    at scheduleUpdateOnFiber (VM207 index.js:93926)
    at updateContainer (VM207 index.js:97100)
    at legacyRenderSubtreeIntoContainer (VM207 index.js:97501)
throwInvalidHookError @ react-dom.development.js:14724
useMemo @ react.development.js:1521
Provider @ Provider.js:10
renderWithHooks @ VM207 index.js:87530
mountIndeterminateComponent @ VM207 index.js:90209
beginWork @ VM207 index.js:91323
callCallback @ VM207 index.js:72915
invokeGuardedCallbackDev @ VM207 index.js:72964
invokeGuardedCallback @ VM207 index.js:73019
beginWork$1 @ VM207 index.js:95930
performUnitOfWork @ VM207 index.js:94881
workLoopSync @ VM207 index.js:94857
performSyncWorkOnRoot @ VM207 index.js:94483
(anonymous) @ VM207 index.js:83816
unstable_runWithPriority @ VM207 index.js:109174
runWithPriority$1 @ VM207 index.js:83766
flushSyncCallbackQueueImpl @ VM207 index.js:83811
flushSyncCallbackQueue @ VM207 index.js:83799
scheduleUpdateOnFiber @ VM207 index.js:93926
dispatchAction @ VM207 index.js:88387
handleAppLeave @ VM207 index.js:49981
AppRoute._this.unmountApp @ VM207 index.js:42247
./node_modules/@ice/stark/lib/AppRoute.js.AppRoute.componentWillUnmount @ VM207 index.js:42311
callComponentWillUnmountWithTimer @ react-dom.development.js:19580
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
safelyCallComponentWillUnmount @ react-dom.development.js:19587
commitUnmount @ react-dom.development.js:20109
commitNestedUnmounts @ react-dom.development.js:20163
unmountHostComponents @ react-dom.development.js:20443
commitDeletion @ react-dom.development.js:20500
commitMutationEffects @ react-dom.development.js:22782
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22509
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
updateContainer @ react-dom.development.js:24373
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24774
render @ react-dom.development.js:24840
_render @ renderer.js:141
renderInBrowser @ renderer.js:128
(anonymous) @ renderer.js:93
step @ renderer.js:33
(anonymous) @ renderer.js:14
(anonymous) @ renderer.js:8
./node_modules/react-app-renderer/lib/renderer.js.__awaiter @ renderer.js:4
reactAppRenderer @ renderer.js:57
runApp @ runApp.ts:61
./src/app.tsx @ app.tsx:56
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ routes.ts:20
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
Show 37 more frames
VM207 index.js:42939 [icestark] can not find app /demo when call unloadMicroApp
VM207 index.js:97796 The above error occurred in the <Provider> component:
    in Provider
    in Provider
    in AuthStoreProvider
    in ConfigProvider
    in addProvider
    in Unknown
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
console.<computed> @ VM207 index.js:97796
console.<computed> @ index.js:1
logCapturedError @ VM207 index.js:92254
logError @ VM207 index.js:92291
update.callback @ VM207 index.js:93435
callCallback @ VM207 index.js:85217
commitUpdateQueue @ VM207 index.js:85238
commitLifeCycles @ VM207 index.js:92610
commitLayoutEffects @ VM207 index.js:95530
callCallback @ VM207 index.js:72915
invokeGuardedCallbackDev @ VM207 index.js:72964
invokeGuardedCallback @ VM207 index.js:73019
commitRootImpl @ VM207 index.js:95268
unstable_runWithPriority @ VM207 index.js:109174
runWithPriority$1 @ VM207 index.js:83766
commitRoot @ VM207 index.js:95108
finishSyncRender @ VM207 index.js:94534
performSyncWorkOnRoot @ VM207 index.js:94520
(anonymous) @ VM207 index.js:83816
unstable_runWithPriority @ VM207 index.js:109174
runWithPriority$1 @ VM207 index.js:83766
flushSyncCallbackQueueImpl @ VM207 index.js:83811
flushSyncCallbackQueue @ VM207 index.js:83799
scheduleUpdateOnFiber @ VM207 index.js:93926
dispatchAction @ VM207 index.js:88387
handleAppLeave @ VM207 index.js:49981
AppRoute._this.unmountApp @ VM207 index.js:42247
./node_modules/@ice/stark/lib/AppRoute.js.AppRoute.componentWillUnmount @ VM207 index.js:42311
callComponentWillUnmountWithTimer @ react-dom.development.js:19580
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
safelyCallComponentWillUnmount @ react-dom.development.js:19587
commitUnmount @ react-dom.development.js:20109
commitNestedUnmounts @ react-dom.development.js:20163
unmountHostComponents @ react-dom.development.js:20443
commitDeletion @ react-dom.development.js:20500
commitMutationEffects @ react-dom.development.js:22782
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22509
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
updateContainer @ react-dom.development.js:24373
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24774
render @ react-dom.development.js:24840
_render @ renderer.js:141
renderInBrowser @ renderer.js:128
(anonymous) @ renderer.js:93
step @ renderer.js:33
(anonymous) @ renderer.js:14
(anonymous) @ renderer.js:8
./node_modules/react-app-renderer/lib/renderer.js.__awaiter @ renderer.js:4
reactAppRenderer @ renderer.js:57
runApp @ runApp.ts:61
./src/app.tsx @ app.tsx:56
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ routes.ts:20
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
Show 42 more frames
VM207 index.js:83829 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (VM207 index.js:87451)
    at useMemo (VM207 index.js:106149)
    at Provider (VM207 index.js:99315)
    at renderWithHooks (VM207 index.js:87530)
    at mountIndeterminateComponent (VM207 index.js:90209)
    at beginWork (VM207 index.js:91323)
    at HTMLUnknownElement.callCallback (VM207 index.js:72915)
    at Object.invokeGuardedCallbackDev (VM207 index.js:72964)
    at invokeGuardedCallback (VM207 index.js:73019)
    at beginWork$1 (VM207 index.js:95930)
    at performUnitOfWork (VM207 index.js:94881)
    at workLoopSync (VM207 index.js:94857)
    at performSyncWorkOnRoot (VM207 index.js:94483)
    at VM207 index.js:83816
    at unstable_runWithPriority (VM207 index.js:109174)
    at runWithPriority$1 (VM207 index.js:83766)
    at flushSyncCallbackQueueImpl (VM207 index.js:83811)
    at flushSyncCallbackQueue (VM207 index.js:83799)
    at scheduleUpdateOnFiber (VM207 index.js:93926)
    at dispatchAction (VM207 index.js:88387)
    at handleAppLeave (VM207 index.js:49981)
    at AppRoute._this.unmountApp (VM207 index.js:42247)
    at AppRoute../node_modules/@ice/stark/lib/AppRoute.js.AppRoute.componentWillUnmount (VM207 index.js:42311)
    at callComponentWillUnmountWithTimer (VM207 index.js:92307)
    at HTMLUnknownElement.callCallback (VM207 index.js:72915)
    at Object.invokeGuardedCallbackDev (VM207 index.js:72964)
    at invokeGuardedCallback (VM207 index.js:73019)
    at safelyCallComponentWillUnmount (VM207 index.js:92314)
    at commitUnmount (VM207 index.js:92836)
    at commitNestedUnmounts (VM207 index.js:92890)
    at unmountHostComponents (VM207 index.js:93170)
    at commitDeletion (VM207 index.js:93227)
    at commitMutationEffects (VM207 index.js:95509)
    at HTMLUnknownElement.callCallback (VM207 index.js:72915)
    at Object.invokeGuardedCallbackDev (VM207 index.js:72964)
    at invokeGuardedCallback (VM207 index.js:73019)
    at commitRootImpl (VM207 index.js:95236)
    at unstable_runWithPriority (VM207 index.js:109174)
    at runWithPriority$1 (VM207 index.js:83766)
    at commitRoot (VM207 index.js:95108)
    at finishSyncRender (VM207 index.js:94534)
    at performSyncWorkOnRoot (VM207 index.js:94520)
    at VM207 index.js:83816
    at unstable_runWithPriority (VM207 index.js:109174)
    at runWithPriority$1 (VM207 index.js:83766)
    at flushSyncCallbackQueueImpl (VM207 index.js:83811)
    at flushSyncCallbackQueue (VM207 index.js:83799)
    at scheduleUpdateOnFiber (VM207 index.js:93926)
    at updateContainer (VM207 index.js:97100)
    at legacyRenderSubtreeIntoContainer (VM207 index.js:97501)
throwInvalidHookError @ react-dom.development.js:14724
useMemo @ react.development.js:1521
Provider @ Provider.js:10
renderWithHooks @ VM207 index.js:87530
mountIndeterminateComponent @ VM207 index.js:90209
beginWork @ VM207 index.js:91323
callCallback @ VM207 index.js:72915
invokeGuardedCallbackDev @ VM207 index.js:72964
invokeGuardedCallback @ VM207 index.js:73019
beginWork$1 @ VM207 index.js:95930
performUnitOfWork @ VM207 index.js:94881
workLoopSync @ VM207 index.js:94857
performSyncWorkOnRoot @ VM207 index.js:94483
(anonymous) @ VM207 index.js:83816
unstable_runWithPriority @ VM207 index.js:109174
runWithPriority$1 @ VM207 index.js:83766
flushSyncCallbackQueueImpl @ VM207 index.js:83811
flushSyncCallbackQueue @ VM207 index.js:83799
scheduleUpdateOnFiber @ VM207 index.js:93926
dispatchAction @ VM207 index.js:88387
handleAppLeave @ VM207 index.js:49981
AppRoute._this.unmountApp @ VM207 index.js:42247
./node_modules/@ice/stark/lib/AppRoute.js.AppRoute.componentWillUnmount @ VM207 index.js:42311
callComponentWillUnmountWithTimer @ react-dom.development.js:19580
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
safelyCallComponentWillUnmount @ react-dom.development.js:19587
commitUnmount @ react-dom.development.js:20109
commitNestedUnmounts @ react-dom.development.js:20163
unmountHostComponents @ react-dom.development.js:20443
commitDeletion @ react-dom.development.js:20500
commitMutationEffects @ react-dom.development.js:22782
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22509
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
updateContainer @ react-dom.development.js:24373
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24774
render @ react-dom.development.js:24840
_render @ renderer.js:141
renderInBrowser @ renderer.js:128
(anonymous) @ renderer.js:93
step @ renderer.js:33
(anonymous) @ renderer.js:14
(anonymous) @ renderer.js:8
./node_modules/react-app-renderer/lib/renderer.js.__awaiter @ renderer.js:4
reactAppRenderer @ renderer.js:57
runApp @ runApp.ts:61
./src/app.tsx @ app.tsx:56
__webpack_require__ @ bootstrap:789
fn @ bootstrap:100
1 @ routes.ts:20
__webpack_require__ @ bootstrap:789
(anonymous) @ bootstrap:856
(anonymous) @ bootstrap:856
Show 37 more frames
react-dom.development.js:7607 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChildFromContainer (http://localhost:3335/js/index.js:80334:15)
    at unmountHostComponents (http://localhost:3335/js/index.js:93174:9)
    at commitDeletion (http://localhost:3335/js/index.js:93227:5)
    at commitMutationEffects (http://localhost:3335/js/index.js:95509:11)
    at HTMLUnknownElement.callCallback (http://localhost:3335/js/index.js:72915:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3335/js/index.js:72964:16)
    at invokeGuardedCallback (http://localhost:3335/js/index.js:73019:31)
    at commitRootImpl (http://localhost:3335/js/index.js:95236:9)
    at unstable_runWithPriority (http://localhost:3335/js/index.js:109174:12)
    at runWithPriority$1 (http://localhost:3335/js/index.js:83766:10)
    at commitRoot (http://localhost:3335/js/index.js:95108:3)
    at finishSyncRender (http://localhost:3335/js/index.js:94534:3)
    at performSyncWorkOnRoot (http://localhost:3335/js/index.js:94520:7)
    at http://localhost:3335/js/index.js:83816:24
    at unstable_runWithPriority (http://localhost:3335/js/index.js:109174:12)
    at runWithPriority$1 (http://localhost:3335/js/index.js:83766:10)
    at flushSyncCallbackQueueImpl (http://localhost:3335/js/index.js:83811:7)
    at flushSyncCallbackQueue (http://localhost:3335/js/index.js:83799:3)
    at scheduleUpdateOnFiber (http://localhost:3335/js/index.js:93926:9)
    at updateContainer (http://localhost:3335/js/index.js:97100:3)
    at legacyRenderSubtreeIntoContainer (http://localhost:3335/js/index.js:97501:5)
    at Object.render (http://localhost:3335/js/index.js:97567:10)
    at _render (http://localhost:3335/js/index.js:72667:71)
    at renderInBrowser (http://localhost:3335/js/index.js:72654:16)
    at http://localhost:3335/js/index.js:72619:21
    at step (http://localhost:3335/js/index.js:72559:23)
    at Object.next (http://localhost:3335/js/index.js:72540:53)
    at http://localhost:3335/js/index.js:72534:71
    at new Promise (<anonymous>)
    at ./node_modules/react-app-renderer/lib/renderer.js.__awaiter (http://localhost:3335/js/index.js:72530:12)
    at reactAppRenderer (http://localhost:3335/js/index.js:72583:12)
    at runApp (http://localhost:3335/js/index.js:1874:3)
    at Module../src/app.tsx (http://localhost:3335/js/index.js:119112:53)
    at __webpack_require__ (http://localhost:3335/js/index.js:790:30)
    at fn (http://localhost:3335/js/index.js:101:20)
    at Object.1 (http://localhost:3335/js/index.js:119950:18)
    at __webpack_require__ (http://localhost:3335/js/index.js:790:30)
    at http://localhost:3335/js/index.js:857:37
    at http://localhost:3335/js/index.js:860:10
```

### PR DESCRIPTION
**Pull request by maoxiaoke**
✅ Closes: Close #233

### CODE REVIEW

File: src/util/handleAssets.ts [hunk 1]
```diff
@@ -231,12 +231,20 @@ export function processHtml(html: string, entry?: string): ProcessedContent {
 
   const domContent = (new DOMParser()).parseFromString(html.replace(COMMENT_REGEX, ''), 'text/html');
 
+  if (entry) {
+    // add base URI for absolute resource. see more https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
+    const base = document.createElement('base');
```
Comment (ClarkXia) [inline src/util/handleAssets.ts:236]: base 插入对于当前页面的是不是有影响
