### PR TITLE
fix: 🐛 append missing styles

### LINKED ISSUE #555: 跳转路由后，微应用样式丢失
主应用和微应用都是官方提供的demo，只修改了引用的地址，其他的并没有修改，但是自己引用的微应用在切换路由后样式会丢失，而waiter引用的那个地址却没有这个问题，是微应用需要配置什么东西吗
image
image

### PR DESCRIPTION
**Pull request by maoxiaoke**
Closes #555

### CODE REVIEW

File: packages/icestark/src/apps.ts [hunk 1]
```diff
@@ -380,7 +380,12 @@ export async function createMicroApp(
       break;
     case UNMOUNTED:
       if (!appConfig.cached) {
-        await loadAndAppendCssAssets(appConfig?.appAssets?.cssList || [], {
+        const appendAssets = [
+          ...appConfig?.appAssets?.cssList || [],
+          ...(appConfig?.loadScriptMode === 'import' ? filterRemovedAssets(importCachedAssets[appConfig.name] ?? [], ['LINK', 'STYLE']) : []),
```
Comment (ClarkXia) [inline packages/icestark/src/apps.ts:385]: 增加下注释说明和 changelog
